#!/bin/sh /etc/rc.common
# Copyright (C) 2020 Nabin Thomas

# Based on documentation here: https://openwrt.org/docs/techref/initscripts
START=99

start() {        
        starttime=`date`
        echo "$starttime : Starting AmazeRT Service" >> /var/log/amazert.log
        /usr/bin/amazert/runner.sh &
}      
